name: GitHub Actions Demo 
run-name: ${{ github.actor }} тестує GitHub Actions 🚀 
on: [push] 
jobs: 
  Explore-GitHub-Actions: 
    runs-on: ubuntu-latest 
    steps: 
      - run: echo " 🎉 Завдання було автоматично ініційовано подією ${{ github.event_name }}." 
      - run: echo "🐧 Це завдання зараз виконується на сервері ${{ runner.os }}, розміщеному на GitHub!" 
      - run: echo "🔎 Назва вашої гілки – ${{ github.ref }}, а ваше сховище – ${{ github.repository }}." 
      - ім'я: код перевірки репозиторію 
        використовує: actions/checkout@v4 
      - запуск: echo "💡 Репозиторій ${{ github.repository }} клоновано до раннера." 
      - run: echo "🖥️ Тепер робочий процес готовий для тестування вашого коду на бігуні." 
      - ім'я: список файлів у репозиторії, 
        запуск: | 
          ls ${{ github.workspace }} 
      - run: echo "🍏 Статус цієї роботи ${{ job.status }}."
